# Generated by Django 5.1.3 on 2026-03-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
