# Generated by Django 5.1.3 on 2026-03-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='experience_certificates/'),
        ),
    ]
